from __future__ import annotations

import threading
from datetime import UTC, datetime, timedelta

import uvicorn

from ysa_gateway.app import create_app
from ysa_gateway.config import Settings
from ysa_gateway.core import (
    ChatMessage,
    ChatReplayPage,
    GatewayError,
    TranscriptSegment,
    TranscriptSegmentPage,
    TranscriptTrack,
    TranscriptTrackPage,
)


class FixtureChatProvider:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._failures: dict[str, int] = {}

    def ready(self) -> bool:
        return True

    def get_page(self, video_id: str, continuation: str | None) -> ChatReplayPage:
        if video_id.startswith("failchat"):
            with self._lock:
                attempt = self._failures.get(video_id, 0) + 1
                self._failures[video_id] = attempt
            if attempt == 1:
                raise GatewayError(
                    status=503,
                    code="YOUTUBE_TEMPORARILY_UNAVAILABLE",
                    detail="temporary fixture failure",
                    retryable=True,
                )

        start = datetime(2026, 1, 1, 0, 1, tzinfo=UTC)
        if continuation is None:
            return ChatReplayPage(
                messages=[
                    _chat("message-2", "Second user", "second page boundary", start + timedelta(seconds=2)),
                    _chat("message-1", "First user", "first message", start + timedelta(seconds=1)),
                ],
                continuation="page-2",
            )
        return ChatReplayPage(
            messages=[
                _chat("message-3", "Third user", "third message", start + timedelta(seconds=3))
            ],
            continuation=None,
        )


class FixtureTranscriptProvider:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._failures: dict[str, int] = {}

    def ready(self) -> bool:
        return True

    def list_tracks(self, video_id: str) -> TranscriptTrackPage:
        if video_id.startswith("m3none"):
            return TranscriptTrackPage(tracks=[])
        if video_id.startswith("m4colfail"):
            raise GatewayError(
                status=502,
                code="YOUTUBE_SOURCE_CHANGED",
                detail="M4 permanent transcript fixture failure",
                retryable=False,
            )
        if video_id.startswith("m3fail"):
            with self._lock:
                attempt = self._failures.get(video_id, 0) + 1
                self._failures[video_id] = attempt
            if attempt == 1:
                raise GatewayError(
                    status=503,
                    code="YOUTUBE_TEMPORARILY_UNAVAILABLE",
                    detail="temporary transcript failure",
                    retryable=True,
                )
        return TranscriptTrackPage(
            tracks=[
                TranscriptTrack(
                    id="ja-manual",
                    languageCode="ja",
                    displayName="日本語",
                    isAutoGenerated=False,
                )
            ]
        )

    def get_page(
        self,
        video_id: str,
        track_id: str,
        continuation: str | None,
    ) -> TranscriptSegmentPage:
        if track_id != "ja-manual":
            raise GatewayError(
                status=400,
                code="INVALID_REQUEST",
                detail="unknown fixture track",
                retryable=False,
            )
        if continuation == "page-2":
            return TranscriptSegmentPage(
                segments=[
                    TranscriptSegment(
                        id="segment-3",
                        startMilliseconds=180000,
                        endMilliseconds=184000,
                        text="重要な検索対象の字幕",
                    )
                ],
                continuation=None,
            )
        return TranscriptSegmentPage(
            segments=[
                TranscriptSegment(
                    id="segment-2",
                    startMilliseconds=125000,
                    endMilliseconds=129000,
                    text="現在位置の字幕",
                ),
                TranscriptSegment(
                    id="segment-1",
                    startMilliseconds=1000,
                    endMilliseconds=5000,
                    text="最初の字幕",
                ),
            ],
            continuation="page-2",
        )


def _chat(
    message_id: str,
    author: str,
    text: str,
    published_at: datetime,
) -> ChatMessage:
    return ChatMessage(
        id=message_id,
        authorChannelId=f"author-{message_id}",
        authorName=author,
        text=text,
        publishedAt=published_at,
    )


if __name__ == "__main__":
    settings = Settings(
        bearer_tokens=("e2e-gateway-token",),
        continuation_secret="e2e-continuation-secret-value-0001",
        host="127.0.0.1",
        port=18081,
    )
    uvicorn.run(
        create_app(settings, FixtureChatProvider(), FixtureTranscriptProvider()),
        host=settings.host,
        port=settings.port,
        access_log=False,
    )
