from __future__ import annotations

import json
import threading
from collections.abc import Iterator
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

import pytest

from ysa_worker.transcript import (
    TranscriptAccessDenied,
    TranscriptGateway,
    TranscriptProtocolError,
    TranscriptTemporaryError,
    TranscriptTrack,
    TranscriptUnavailable,
    parse_segment_page,
    parse_tracks,
    select_track,
)


class FixtureHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        assert self.headers.get("Authorization") == "Bearer gateway-token"
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        video_id = query.get("videoId", [""])[0]
        if video_id == "temporary01":
            self._problem(503, "SOURCE_NOT_READY", True)
            return
        if video_id == "denied00001":
            self._problem(403, "YOUTUBE_ACCESS_DENIED", False)
            return
        if video_id == "missing0001":
            self._problem(404, "TRANSCRIPT_NOT_AVAILABLE", False)
            return
        if parsed.path == "/v1/transcripts/tracks":
            tracks = (
                []
                if video_id == "notracks001"
                else [
                    {
                        "id": "ja-auto",
                        "languageCode": "ja",
                        "displayName": "Japanese (auto-generated)",
                        "isAutoGenerated": True,
                    },
                    {
                        "id": "en-manual",
                        "languageCode": "en",
                        "displayName": "English",
                        "isAutoGenerated": False,
                    },
                    {
                        "id": "ja-manual",
                        "languageCode": "ja",
                        "displayName": "日本語",
                        "isAutoGenerated": False,
                    },
                ]
            )
            self._json({"tracks": tracks})
            return
        if parsed.path == "/v1/transcripts/segments":
            continuation = query.get("continuation", [None])[0]
            if continuation is None:
                self._json(
                    {
                        "segments": [
                            {
                                "id": "segment-2",
                                "startMilliseconds": 2000,
                                "endMilliseconds": 3100,
                                "text": "second",
                            }
                        ],
                        "continuation": "page-2",
                    }
                )
            else:
                self._json(
                    {
                        "segments": [
                            {
                                "id": "segment-1",
                                "startMilliseconds": 1000,
                                "endMilliseconds": 1900,
                                "text": "first",
                            }
                        ],
                        "continuation": None,
                    }
                )
            return
        self.send_error(404)

    def _json(self, payload: object) -> None:
        body = json.dumps(payload).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _problem(self, status: int, code: str, retryable: bool) -> None:
        body = json.dumps(
            {
                "type": f"urn:gateway:{code.lower()}",
                "title": code,
                "status": status,
                "detail": code.lower(),
                "code": code,
                "retryable": retryable,
                "requestId": "request-1",
            }
        ).encode()
        self.send_response(status)
        self.send_header("Content-Type", "application/problem+json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, _format: str, *_args: object) -> None:
        return


@pytest.fixture
def fixture_url() -> Iterator[str]:
    server = ThreadingHTTPServer(("127.0.0.1", 0), FixtureHandler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=2)


def test_select_track_prefers_japanese_manual() -> None:
    tracks = (
        TranscriptTrack("en-manual", "en", "English", False),
        TranscriptTrack("ja-auto", "ja", "Japanese auto", True),
        TranscriptTrack("ja-manual", "ja", "日本語", False),
    )
    assert select_track(tracks) == tracks[2]


def test_collects_all_pages_and_sorts_segments(fixture_url: str) -> None:
    result = TranscriptGateway(fixture_url, "gateway-token").collect("captions001")
    assert result.track is not None
    assert result.track.external_id == "ja-manual"
    assert [item.external_id for item in result.segments] == ["segment-1", "segment-2"]
    assert result.segments[0].start_milliseconds == 1000
    assert result.segments[0].end_milliseconds == 1900


def test_no_tracks_is_normal_result(fixture_url: str) -> None:
    result = TranscriptGateway(fixture_url, "gateway-token").collect("notracks001")
    assert result.has_transcript is False
    assert result.track is None
    assert result.segments == ()


@pytest.mark.parametrize(
    ("video_id", "error_type"),
    [
        ("temporary01", TranscriptTemporaryError),
        ("denied00001", TranscriptAccessDenied),
        ("missing0001", TranscriptUnavailable),
    ],
)
def test_classifies_problem_details(
    fixture_url: str, video_id: str, error_type: type[Exception]
) -> None:
    with pytest.raises(error_type):
        TranscriptGateway(fixture_url, "gateway-token").collect(video_id)


def test_rejects_invalid_external_payloads() -> None:
    with pytest.raises(TranscriptProtocolError):
        parse_tracks({"tracks": [{"id": "broken"}]})
    with pytest.raises(TranscriptProtocolError):
        parse_segment_page(
            {
                "segments": [
                    {
                        "id": "broken",
                        "startMilliseconds": 2000,
                        "endMilliseconds": 1000,
                        "text": "invalid",
                    }
                ]
            }
        )
