from __future__ import annotations

import base64
import hashlib
import hmac
import json
from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class GatewayError(RuntimeError):
    def __init__(
        self,
        *,
        status: int,
        code: str,
        detail: str,
        retryable: bool,
        retry_after: int | None = None,
    ) -> None:
        super().__init__(detail)
        self.status = status
        self.code = code
        self.detail = detail
        self.retryable = retryable
        self.retry_after = retry_after


class ProbeResponse(BaseModel):
    model_config = ConfigDict(extra="forbid")
    status: Literal["ok"] = "ok"


class ChatMessage(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str
    author_channel_id: str | None = Field(alias="authorChannelId")
    author_name: str = Field(alias="authorName")
    text: str
    published_at: datetime = Field(alias="publishedAt")


class ChatReplayPage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    messages: list[ChatMessage]
    continuation: str | None


class TranscriptTrack(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str
    language_code: str = Field(alias="languageCode")
    display_name: str = Field(alias="displayName")
    is_auto_generated: bool = Field(alias="isAutoGenerated")


class TranscriptTrackPage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    tracks: list[TranscriptTrack]


class TranscriptSegment(BaseModel):
    model_config = ConfigDict(extra="forbid", populate_by_name=True)
    id: str
    start_milliseconds: int = Field(alias="startMilliseconds")
    end_milliseconds: int = Field(alias="endMilliseconds")
    text: str


class TranscriptSegmentPage(BaseModel):
    model_config = ConfigDict(extra="forbid")
    segments: list[TranscriptSegment]
    continuation: str | None


class TokenCodec:
    def __init__(self, secret: str) -> None:
        self._secret = secret.encode("utf-8")

    def encode(self, kind: str, payload: dict[str, Any]) -> str:
        envelope = {"version": 1, "kind": kind, "payload": payload}
        raw = json.dumps(
            envelope,
            ensure_ascii=False,
            separators=(",", ":"),
            sort_keys=True,
        ).encode("utf-8")
        signature = hmac.new(self._secret, raw, hashlib.sha256).digest()
        return f"{_b64encode(raw)}.{_b64encode(signature)}"

    def decode(self, token: str, expected_kind: str) -> dict[str, Any]:
        try:
            encoded_payload, encoded_signature = token.split(".", 1)
            raw = _b64decode(encoded_payload)
            signature = _b64decode(encoded_signature)
        except (ValueError, UnicodeError) as error:
            raise _invalid_token() from error

        expected_signature = hmac.new(self._secret, raw, hashlib.sha256).digest()
        if not hmac.compare_digest(signature, expected_signature):
            raise _invalid_token()

        try:
            envelope = json.loads(raw)
        except (json.JSONDecodeError, UnicodeDecodeError) as error:
            raise _invalid_token() from error
        if not isinstance(envelope, dict):
            raise _invalid_token()
        if envelope.get("version") != 1 or envelope.get("kind") != expected_kind:
            raise _invalid_token()
        payload = envelope.get("payload")
        if not isinstance(payload, dict):
            raise _invalid_token()
        return payload


def _invalid_token() -> GatewayError:
    return GatewayError(
        status=400,
        code="INVALID_REQUEST",
        detail="continuation or track identifier is invalid",
        retryable=False,
    )


def _b64encode(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).rstrip(b"=").decode("ascii")


def _b64decode(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value + padding)
