from __future__ import annotations

import hashlib
from collections.abc import Iterable
from typing import Any

from youtube_transcript_api import YouTubeTranscriptApi
from youtube_transcript_api._errors import (
    CouldNotRetrieveTranscript,
    TranscriptsDisabled,
)

from .config import Settings
from .core import (
    GatewayError,
    TokenCodec,
    TranscriptSegment,
    TranscriptSegmentPage,
    TranscriptTrack,
    TranscriptTrackPage,
)
from .provider_support import build_session, invalid_request, map_transcript_error


class YoutubeTranscriptProvider:
    def __init__(
        self,
        settings: Settings,
        codec: TokenCodec,
        transcript_api: Any | None = None,
    ) -> None:
        self._settings = settings
        self._codec = codec
        self._session = build_session(settings)
        self._api = transcript_api or YouTubeTranscriptApi(http_client=self._session)

    def ready(self) -> bool:
        return self._settings.readiness_error() is None

    def list_tracks(self, video_id: str) -> TranscriptTrackPage:
        try:
            transcript_list = self._api.list(video_id)
            tracks = [self._to_track(video_id, track) for track in transcript_list]
        except TranscriptsDisabled:
            tracks = []
        except CouldNotRetrieveTranscript as error:
            raise map_transcript_error(error) from error
        return TranscriptTrackPage(tracks=tracks)

    def get_page(
        self, video_id: str, track_id: str, continuation: str | None
    ) -> TranscriptSegmentPage:
        offset = self._decode_offset(video_id, track_id, continuation)
        try:
            transcript_list = self._api.list(video_id)
            selected = self._select_transcript(video_id, track_id, transcript_list)
            fetched = selected.fetch()
        except TranscriptsDisabled:
            raise _transcript_not_available() from None
        except CouldNotRetrieveTranscript as error:
            raise map_transcript_error(error) from error

        all_segments = _normalize_transcript_segments(track_id, fetched)
        page_size = self._settings.transcript_page_size
        page = all_segments[offset : offset + page_size]
        next_offset = offset + len(page)
        next_token = None
        if next_offset < len(all_segments):
            next_token = self._codec.encode(
                "transcript-page",
                {"videoId": video_id, "trackId": track_id, "offset": next_offset},
            )
        return TranscriptSegmentPage(segments=page, continuation=next_token)

    def _decode_offset(
        self,
        video_id: str,
        track_id: str,
        continuation: str | None,
    ) -> int:
        if continuation is None:
            return 0
        page_payload = self._codec.decode(continuation, "transcript-page")
        if (
            page_payload.get("videoId") != video_id
            or page_payload.get("trackId") != track_id
        ):
            raise invalid_request("transcript continuation does not match the track")
        raw_offset = page_payload.get("offset")
        if not isinstance(raw_offset, int) or raw_offset < 0:
            raise invalid_request("transcript continuation offset is invalid")
        return raw_offset

    def _to_track(self, video_id: str, track: Any) -> TranscriptTrack:
        language_code = str(track.language_code)
        display_name = str(track.language)
        is_generated = bool(track.is_generated)
        return TranscriptTrack(
            id=_track_id(video_id, language_code, display_name, is_generated),
            languageCode=language_code,
            displayName=display_name,
            isAutoGenerated=is_generated,
        )

    def _select_transcript(
        self,
        video_id: str,
        track_id: str,
        transcript_list: Iterable[Any],
    ) -> Any:
        for transcript in transcript_list:
            candidate_id = _track_id(
                video_id,
                str(transcript.language_code),
                str(transcript.language),
                bool(transcript.is_generated),
            )
            if candidate_id == track_id:
                return transcript
        raise _transcript_not_available()


def _track_id(
    video_id: str,
    language_code: str,
    display_name: str,
    is_generated: bool,
) -> str:
    value = f"{video_id}\0{language_code}\0{display_name}\0{int(is_generated)}"
    return hashlib.sha256(value.encode()).hexdigest()


def _normalize_transcript_segments(
    track_id: str,
    fetched: Iterable[Any],
) -> list[TranscriptSegment]:
    segments: list[TranscriptSegment] = []
    for index, snippet in enumerate(fetched):
        text = str(snippet.text).strip()
        if not text:
            continue
        start = max(0, round(float(snippet.start) * 1000))
        end = max(
            start + 1,
            round((float(snippet.start) + float(snippet.duration)) * 1000),
        )
        digest = hashlib.sha256(
            f"{track_id}\0{index}\0{start}\0{end}\0{text}".encode()
        ).hexdigest()
        segments.append(
            TranscriptSegment(
                id=digest,
                startMilliseconds=start,
                endMilliseconds=end,
                text=text[:20000],
            )
        )
    return segments


def _transcript_not_available() -> GatewayError:
    return GatewayError(
        status=404,
        code="TRANSCRIPT_NOT_AVAILABLE",
        detail="transcript is not available",
        retryable=False,
    )
