package transcript

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5/pgxpool"
)

var ErrStreamNotFound = errors.New("stream not found")

type Segment struct {
	ID                      string `json:"id"`
	TrackID                 string `json:"trackId"`
	LanguageCode            string `json:"languageCode"`
	IsAutoGenerated         bool   `json:"isAutoGenerated"`
	SourceSegmentID         string `json:"sourceSegmentId"`
	StartOffsetMilliseconds int64  `json:"startOffsetMilliseconds"`
	EndOffsetMilliseconds   int64  `json:"endOffsetMilliseconds"`
	Text                    string `json:"text"`
}

type Page struct {
	Items      []Segment `json:"items"`
	NextCursor *string   `json:"nextCursor"`
}

type cursor struct {
	Start int64  `json:"s"`
	ID    string `json:"i"`
}

type Repository struct{ db *pgxpool.Pool }

func NewRepository(db *pgxpool.Pool) *Repository { return &Repository{db: db} }

func (r *Repository) List(ctx context.Context, streamID string, limit int, cursorValue string) (Page, error) {
	if err := r.requireStream(ctx, streamID); err != nil {
		return Page{}, err
	}
	query := `SELECT s.id,s.track_id,t.language_code,t.is_auto_generated,s.source_segment_id,
		s.start_offset_milliseconds,s.end_offset_milliseconds,s.text
		FROM transcript.transcript_segments s
		JOIN transcript.transcript_tracks t ON t.id=s.track_id
		WHERE s.stream_id=$1 AND t.is_selected`
	args := []any{streamID}
	if cursorValue != "" {
		after, err := decodeCursor(cursorValue)
		if err != nil {
			return Page{}, err
		}
		query += ` AND (s.start_offset_milliseconds,s.id) > ($2,$3)`
		args = append(args, after.Start, after.ID)
	}
	query += fmt.Sprintf(` ORDER BY s.start_offset_milliseconds,s.id LIMIT $%d`, len(args)+1)
	args = append(args, limit+1)
	return r.queryPage(ctx, query, args, limit)
}

func (r *Repository) Range(ctx context.Context, streamID string, fromMS, toMS int64) ([]Segment, error) {
	if err := r.requireStream(ctx, streamID); err != nil {
		return nil, err
	}
	rows, err := r.db.Query(ctx, `SELECT s.id,s.track_id,t.language_code,t.is_auto_generated,s.source_segment_id,
		s.start_offset_milliseconds,s.end_offset_milliseconds,s.text
		FROM transcript.transcript_segments s
		JOIN transcript.transcript_tracks t ON t.id=s.track_id
		WHERE s.stream_id=$1 AND t.is_selected
		AND s.start_offset_milliseconds < $3 AND s.end_offset_milliseconds > $2
		ORDER BY s.start_offset_milliseconds,s.id`, streamID, fromMS, toMS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Segment{}
	for rows.Next() {
		var item Segment
		if err := rows.Scan(&item.ID, &item.TrackID, &item.LanguageCode, &item.IsAutoGenerated, &item.SourceSegmentID, &item.StartOffsetMilliseconds, &item.EndOffsetMilliseconds, &item.Text); err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	return items, rows.Err()
}

func (r *Repository) requireStream(ctx context.Context, streamID string) error {
	var exists bool
	if err := r.db.QueryRow(ctx, `SELECT EXISTS(SELECT 1 FROM stream.streams WHERE id=$1)`, streamID).Scan(&exists); err != nil {
		return err
	}
	if !exists {
		return ErrStreamNotFound
	}
	return nil
}

func (r *Repository) queryPage(ctx context.Context, query string, args []any, limit int) (Page, error) {
	rows, err := r.db.Query(ctx, query, args...)
	if err != nil {
		return Page{}, err
	}
	defer rows.Close()
	items := make([]Segment, 0, limit+1)
	for rows.Next() {
		var item Segment
		if err := rows.Scan(&item.ID, &item.TrackID, &item.LanguageCode, &item.IsAutoGenerated, &item.SourceSegmentID, &item.StartOffsetMilliseconds, &item.EndOffsetMilliseconds, &item.Text); err != nil {
			return Page{}, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return Page{}, err
	}
	page := Page{Items: items}
	if len(items) > limit {
		last := items[limit-1]
		value, err := encodeCursor(cursor{Start: last.StartOffsetMilliseconds, ID: last.ID})
		if err != nil {
			return Page{}, err
		}
		page.Items = items[:limit]
		page.NextCursor = &value
	}
	return page, nil
}

func encodeCursor(value cursor) (string, error) {
	encoded, err := json.Marshal(value)
	if err != nil {
		return "", err
	}
	return base64.RawURLEncoding.EncodeToString(encoded), nil
}

func decodeCursor(value string) (cursor, error) {
	decoded, err := base64.RawURLEncoding.DecodeString(value)
	if err != nil {
		return cursor{}, err
	}
	var result cursor
	if err := json.Unmarshal(decoded, &result); err != nil {
		return cursor{}, err
	}
	if result.ID == "" || result.Start < 0 {
		return cursor{}, errors.New("invalid cursor")
	}
	return result, nil
}
