from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from ysa_worker.gateway_http import GatewayHTTPError, get_json


class TranscriptError(RuntimeError):
    code = "TRANSCRIPT_ERROR"
    retryable = False


class TranscriptAccessDenied(TranscriptError):
    code = "TRANSCRIPT_ACCESS_DENIED"


class TranscriptUnavailable(TranscriptError):
    code = "TRANSCRIPT_UNAVAILABLE"


class TranscriptTemporaryError(TranscriptError):
    code = "TRANSCRIPT_TEMPORARILY_UNAVAILABLE"
    retryable = True


class TranscriptProtocolError(TranscriptError):
    code = "TRANSCRIPT_SOURCE_CHANGED"


class TranscriptAuthenticationError(TranscriptError):
    code = "TRANSCRIPT_GATEWAY_UNAUTHORIZED"


@dataclass(frozen=True)
class TranscriptTrack:
    external_id: str
    language_code: str
    display_name: str
    is_auto_generated: bool


@dataclass(frozen=True)
class TranscriptSegment:
    external_id: str
    start_milliseconds: int
    end_milliseconds: int
    text: str


@dataclass(frozen=True)
class TranscriptResult:
    track: TranscriptTrack | None
    segments: tuple[TranscriptSegment, ...]

    @property
    def has_transcript(self) -> bool:
        return self.track is not None


class TranscriptGateway:
    def __init__(
        self,
        base_url: str,
        bearer_token: str,
        timeout_seconds: float = 15,
    ) -> None:
        self.base_url = base_url.rstrip("/")
        self.bearer_token = bearer_token
        self.timeout_seconds = timeout_seconds

    def collect(self, video_id: str) -> TranscriptResult:
        tracks = self.list_tracks(video_id)
        track = select_track(tracks)
        if track is None:
            return TranscriptResult(track=None, segments=())
        return TranscriptResult(track=track, segments=self.fetch_segments(video_id, track))

    def list_tracks(self, video_id: str) -> tuple[TranscriptTrack, ...]:
        payload = self._get_json(
            "/v1/transcripts/tracks",
            {"videoId": video_id},
        )
        return parse_tracks(payload)

    def fetch_segments(
        self, video_id: str, track: TranscriptTrack
    ) -> tuple[TranscriptSegment, ...]:
        continuation: str | None = None
        seen: set[str] = set()
        segments: list[TranscriptSegment] = []
        for _ in range(10_000):
            query = {"videoId": video_id, "trackId": track.external_id}
            if continuation:
                query["continuation"] = continuation
            payload = self._get_json("/v1/transcripts/segments", query)
            page, continuation = parse_segment_page(payload)
            segments.extend(page)
            if continuation is None:
                break
            if continuation in seen:
                raise TranscriptProtocolError("transcript continuation loop detected")
            seen.add(continuation)
        else:
            raise TranscriptProtocolError("transcript page limit exceeded")
        return tuple(sorted(segments, key=lambda item: (item.start_milliseconds, item.external_id)))

    def _get_json(self, path: str, query: dict[str, str]) -> Any:
        try:
            return get_json(
                self.base_url,
                path,
                query,
                self.bearer_token,
                self.timeout_seconds,
            )
        except GatewayHTTPError as error:
            raise _map_gateway_error(error) from error


def select_track(tracks: tuple[TranscriptTrack, ...]) -> TranscriptTrack | None:
    if not tracks:
        return None

    def rank(track: TranscriptTrack) -> tuple[int, str, str]:
        is_japanese = track.language_code.lower() == "ja"
        if is_japanese and not track.is_auto_generated:
            priority = 0
        elif is_japanese:
            priority = 1
        elif not track.is_auto_generated:
            priority = 2
        else:
            priority = 3
        return priority, track.language_code.lower(), track.external_id

    return min(tracks, key=rank)


def parse_tracks(payload: Any) -> tuple[TranscriptTrack, ...]:
    if not isinstance(payload, dict):
        raise TranscriptProtocolError("transcript track root must be an object")
    raw_tracks = payload.get("tracks")
    if not isinstance(raw_tracks, list):
        raise TranscriptProtocolError("transcript tracks are missing")
    tracks: list[TranscriptTrack] = []
    for raw in raw_tracks:
        if not isinstance(raw, dict):
            raise TranscriptProtocolError("invalid transcript track")
        external_id = raw.get("id")
        language_code = raw.get("languageCode")
        display_name = raw.get("displayName")
        is_auto_generated = raw.get("isAutoGenerated")
        if not isinstance(external_id, str) or not external_id:
            raise TranscriptProtocolError("transcript track ID is missing")
        if not isinstance(language_code, str) or not language_code:
            raise TranscriptProtocolError("transcript language is missing")
        if not isinstance(display_name, str):
            raise TranscriptProtocolError("transcript display name is missing")
        if not isinstance(is_auto_generated, bool):
            raise TranscriptProtocolError("transcript generation type is missing")
        tracks.append(
            TranscriptTrack(
                external_id=external_id,
                language_code=language_code,
                display_name=display_name,
                is_auto_generated=is_auto_generated,
            )
        )
    return tuple(tracks)


def parse_segment_page(
    payload: Any,
) -> tuple[tuple[TranscriptSegment, ...], str | None]:
    if not isinstance(payload, dict):
        raise TranscriptProtocolError("transcript segment root must be an object")
    raw_segments = payload.get("segments")
    if not isinstance(raw_segments, list):
        raise TranscriptProtocolError("transcript segments are missing")
    continuation = payload.get("continuation")
    if continuation is not None and not isinstance(continuation, str):
        raise TranscriptProtocolError("invalid transcript continuation")
    segments: list[TranscriptSegment] = []
    for raw in raw_segments:
        if not isinstance(raw, dict):
            raise TranscriptProtocolError("invalid transcript segment")
        external_id = raw.get("id")
        start = raw.get("startMilliseconds")
        end = raw.get("endMilliseconds")
        text = raw.get("text")
        if not isinstance(external_id, str) or not external_id:
            raise TranscriptProtocolError("transcript segment ID is missing")
        if not isinstance(start, int) or not isinstance(end, int):
            raise TranscriptProtocolError("transcript segment time is missing")
        if start < 0 or end <= start:
            raise TranscriptProtocolError("invalid transcript segment range")
        if not isinstance(text, str):
            raise TranscriptProtocolError("transcript segment text is missing")
        segments.append(
            TranscriptSegment(
                external_id=external_id,
                start_milliseconds=start,
                end_milliseconds=end,
                text=text,
            )
        )
    return tuple(segments), continuation or None


def _map_gateway_error(error: GatewayHTTPError) -> TranscriptError:
    problem = error.problem
    if problem.code == "GATEWAY_UNAUTHORIZED":
        return TranscriptAuthenticationError(problem.detail)
    if problem.code == "YOUTUBE_ACCESS_DENIED":
        return TranscriptAccessDenied(problem.detail)
    if problem.code == "TRANSCRIPT_NOT_AVAILABLE":
        return TranscriptUnavailable(problem.detail)
    if problem.retryable or problem.code in {
        "SOURCE_NOT_READY",
        "YOUTUBE_RATE_LIMITED",
        "YOUTUBE_TEMPORARILY_UNAVAILABLE",
        "YOUTUBE_TIMEOUT",
        "GATEWAY_NOT_READY",
    }:
        return TranscriptTemporaryError(problem.detail)
    return TranscriptProtocolError(problem.detail)
