package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"sync"
)

func main() {
	addr := os.Getenv("YSA_TRANSCRIPT_STUB_ADDRESS")
	if addr == "" {
		addr = ":18083"
	}
	var mu sync.Mutex
	failedOnce := map[string]bool{}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /tracks", func(w http.ResponseWriter, r *http.Request) {
		videoID := r.URL.Query().Get("videoId")
		w.Header().Set("Content-Type", "application/json")
		if strings.HasPrefix(videoID, "m3none") {
			_, _ = fmt.Fprint(w, `{"tracks":[]}`)
			return
		}
		if strings.HasPrefix(videoID, "m3fail") {
			mu.Lock()
			alreadyFailed := failedOnce[videoID]
			if !alreadyFailed {
				failedOnce[videoID] = true
			}
			mu.Unlock()
			if !alreadyFailed {
				http.Error(w, "temporary transcript failure", http.StatusServiceUnavailable)
				return
			}
		}
		_, _ = fmt.Fprint(w, `{"tracks":[{"id":"ja-manual","languageCode":"ja","displayName":"日本語","isAutoGenerated":false}]}`)
	})
	mux.HandleFunc("GET /segments", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		if r.URL.Query().Get("continuation") == "page-2" {
			_, _ = fmt.Fprint(w, `{"segments":[{"id":"segment-3","startMilliseconds":180000,"endMilliseconds":184000,"text":"重要な検索対象の字幕"}]}`)
			return
		}
		_, _ = fmt.Fprint(w, `{"segments":[{"id":"segment-2","startMilliseconds":125000,"endMilliseconds":129000,"text":"現在位置の字幕"},{"id":"segment-1","startMilliseconds":1000,"endMilliseconds":5000,"text":"最初の字幕"}],"continuation":"page-2"}`)
	})
	log.Printf("Transcript stub listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}
