package main

import (
	"encoding/json"
	"log"
	"net/http"
	"os"
	"strings"
	"sync"
)

func main() {
	addr := os.Getenv("YSA_TRANSCRIPT_STUB_ADDRESS")
	if addr == "" {
		addr = ":18083"
	}
	var mu sync.Mutex
	failedOnce := map[string]bool{}
	mux := http.NewServeMux()
	mux.HandleFunc("GET /v1/transcripts/tracks", func(w http.ResponseWriter, r *http.Request) {
		if !authorized(r) {
			writeProblem(w, http.StatusUnauthorized, "GATEWAY_UNAUTHORIZED", false, "invalid token")
			return
		}
		videoID := r.URL.Query().Get("videoId")
		if strings.HasPrefix(videoID, "m3none") {
			writeJSON(w, http.StatusOK, map[string]any{"tracks": []any{}})
			return
		}
		if strings.HasPrefix(videoID, "m4colfail") {
			writeProblem(
				w,
				http.StatusBadGateway,
				"YOUTUBE_SOURCE_CHANGED",
				false,
				"M4 permanent transcript fixture failure",
			)
			return
		}
		if strings.HasPrefix(videoID, "m3fail") {
			mu.Lock()
			alreadyFailed := failedOnce[videoID]
			if !alreadyFailed {
				failedOnce[videoID] = true
			}
			mu.Unlock()
			if !alreadyFailed {
				writeProblem(
					w,
					http.StatusServiceUnavailable,
					"YOUTUBE_TEMPORARILY_UNAVAILABLE",
					true,
					"temporary transcript failure",
				)
				return
			}
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"tracks": []any{map[string]any{
				"id":              "ja-manual",
				"languageCode":    "ja",
				"displayName":     "日本語",
				"isAutoGenerated": false,
			}},
		})
	})
	mux.HandleFunc("GET /v1/transcripts/segments", func(w http.ResponseWriter, r *http.Request) {
		if !authorized(r) {
			writeProblem(w, http.StatusUnauthorized, "GATEWAY_UNAUTHORIZED", false, "invalid token")
			return
		}
		if r.URL.Query().Get("continuation") == "page-2" {
			writeJSON(w, http.StatusOK, map[string]any{
				"segments": []any{map[string]any{
					"id":                "segment-3",
					"startMilliseconds": 180000,
					"endMilliseconds":   184000,
					"text":              "重要な検索対象の字幕",
				}},
				"continuation": nil,
			})
			return
		}
		writeJSON(w, http.StatusOK, map[string]any{
			"segments": []any{
				map[string]any{
					"id":                "segment-2",
					"startMilliseconds": 125000,
					"endMilliseconds":   129000,
					"text":              "現在位置の字幕",
				},
				map[string]any{
					"id":                "segment-1",
					"startMilliseconds": 1000,
					"endMilliseconds":   5000,
					"text":              "最初の字幕",
				},
			},
			"continuation": "page-2",
		})
	})
	log.Printf("Transcript stub listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, mux))
}

func authorized(r *http.Request) bool {
	token := os.Getenv("YSA_GATEWAY_STUB_TOKEN")
	if token == "" {
		token = "e2e-gateway-token"
	}
	return r.Header.Get("Authorization") == "Bearer "+token
}

func writeProblem(w http.ResponseWriter, status int, code string, retryable bool, detail string) {
	writeJSON(w, status, map[string]any{
		"type":      "urn:youtube-stream-analyzer:gateway:" + strings.ToLower(code),
		"title":     code,
		"status":    status,
		"detail":    detail,
		"code":      code,
		"retryable": retryable,
		"requestId": "e2e-request",
	})
}

func writeJSON(w http.ResponseWriter, status int, payload any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(payload)
}
